version: '3.7'

services:
  dnsmasq:
    image: 4km3/dnsmasq
    container_name: dnsmasq
    command: ["--address=/.localhost/127.0.0.1"]
    networks:
      - traefik-network
    ports:
      - "53:53/udp"  # DNS server to resolve *.localhost

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"     # HTTP
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-network
    depends_on:
      - dnsmasq

networks:
  traefik-network:
    external: true
